export const metadata = {
      title: 'Next.js Website',
      description: 'Generated by create next app',
    }

    export default function RootLayout({ children }) {
      return (
        <html lang="en">
          <body>{children}</body>
        </html>
      )
    }
